# build stage
FROM node:lts-alpine as build-stage
ARG CONFIG_MODE_ENV=staging

WORKDIR /app

COPY ./RemoteFinder.UI/package*.json ./
RUN yarn install

COPY ./RemoteFinder.UI/ .
COPY ./Docker_files/ .

ENV NODE_ENV=production

RUN yarn build-production

# production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/nginx/nginx.conf /etc/nginx
COPY --from=build-stage /app/nginx/default.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]