FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
ARG ASPNETCORE_ENVIRONMENT=Production
ARG BUILD_NUMBER=local

COPY ./USVStudDocs.BLL ./USVStudDocs.BLL
COPY ./USVStudDocs.DAL ./USVStudDocs.DAL
COPY ./USVStudDocs.Entities ./USVStudDocs.Entities
COPY ./USVStudDocs.Models ./USVStudDocs.Models
COPY ./USVStudDocs.Web ./USVStudDocs.Web
COPY ./USVStudDocs.sln ./

WORKDIR /app/USVStudDocs.Web

RUN dotnet restore

RUN dotnet publish -c Release -o out /p:Version="1.0.0-$BUILD_NUMBER"

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app

COPY --from=build-env /app/USVStudDocs.Web/out ./

ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
ENV ASPNETCORE_URLS=http://*:5000

RUN echo $ASPNETCORE_ENVIRONMENT
RUN echo $ASPNETCORE_URLS

ENTRYPOINT ["dotnet", "USVStudDocs.Web.dll"]